---
- name: Install Apache on Ubuntu 20.04
  hosts: 
    - test1
    - test2               # Replace with the appropriate host or group of hosts
  become: yes               # Run tasks with sudo
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache package
      apt:
        name: apache2
        state: present

    - name: Enable Apache service
      systemd:
        name: apache2
        enabled: yes

    - name: Start Apache service
      systemd:
        name:
    - name: Enable Apache service
      systemd:
        name: apache2
        enabled: yes

    - name: Start Apache service
      systemd:
        name: apache2
        state: started